# Generated by Django 4.2.11 on 2024-04-21 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gyoumuhyo", "0003_workarea_alter_employee_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SworkArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="作業エリア")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="日付"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="WorkArea",),
    ]
